const quotes = [
    "The best way to predict the future is to create it. - Peter Drucker",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
    "Don't watch the clock; do what it does. Keep going. - Sam Levenson",
    "The only limit to our realization of tomorrow is our doubts of today. - Franklin D. Roosevelt",
    "The purpose of our lives is to be happy. - Dalai Lama",
    "Life is what happens when you're busy making other plans. - John Lennon",
    "Get busy living or get busy dying. - Stephen King",
    "You only live once, but if you do it right, once is enough. - Mae West",
    "Many of life's failures are people who did not realize how close they were to success when they gave up. - Thomas Edison",
    "If you want to live a happy life, tie it to a goal, not to people or things. - Albert Einstein",
    "Never let the fear of striking out keep you from playing the game. - Babe Ruth",
    "Money and success don't change people; they merely amplify what is already there. - Will Smith",
    "Your time is limited, so don't waste it living someone else's life. - Steve Jobs",
    "Not how long, but how well you have lived is the main thing. - Seneca",
    "If life were predictable it would cease to be life, and be without flavor. - Eleanor Roosevelt",
    "The whole secret of a successful life is to find out what is one's destiny to do, and then do it. - Henry Ford",
    "In order to write about life first you must live it. - Ernest Hemingway",
    "The big lesson in life, baby, is never be scared of anyone or anything. - Frank Sinatra",
    "Sing like no one's listening, love like you've never been hurt, dance like nobody's watching, and live like it's heaven on earth. - Mark Twain",
    "Curiosity about life in all of its aspects, I think, is still the secret of great creative people. - Leo Burnett",
    "Life is not a problem to be solved, but a reality to be experienced. - Søren Kierkegaard",
    "The unexamined life is not worth living. - Socrates",
    "Turn your wounds into wisdom. - Oprah Winfrey",
    "Happiness is not something ready made. It comes from your own actions. - Dalai Lama",
    "Keep calm and carry on. - Winston Churchill",
    "You must be the change you wish to see in the world. - Mahatma Gandhi",
    "Life is really simple, but we insist on making it complicated. - Confucius",
    "May you live all the days of your life. - Jonathan Swift",
    "Life itself is the most wonderful fairy tale. - Hans Christian Andersen",
    "Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment. - Buddha",
    "Life is short, and it is here to be lived. - Kate Winslet",
    "The longer I live, the more I realize that life is not about pleasing others. It's about making sure you please yourself. - Unknown",
    "The biggest adventure you can take is to live the life of your dreams. - Oprah Winfrey",
    "Don't be afraid to give up the good to go for the great. - John D. Rockefeller",
    "It is better to fail in originality than to succeed in imitation. - Herman Melville",
    "The road to success and the road to failure are almost exactly the same. - Colin R. Davis",
    "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
    "Opportunities don't happen. You create them. - Chris Grosser",
    "Don't be afraid to give up the good to go for the great. - John D. Rockefeller",
    "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
    "Success is not in what you have, but who you are. - Bo Bennett",
    "Success is walking from failure to failure with no loss of enthusiasm. - Winston Churchill",
    "Try not to become a man of success. Rather become a man of value. - Albert Einstein",
    "Don't wait for opportunity. Create it. - George Bernard Shaw",
    "Great things never came from comfort zones. - Neil Strauss",
    "Success is liking yourself, liking what you do, and liking how you do it. - Maya Angelou",
    "Don't be distracted by criticism. Remember - the only taste of success some people get is to take a bite out of you. - Zig Ziglar",
    "Success seems to be connected with action. Successful people keep moving. They make mistakes, but they don't quit. - Conrad Hilton",
    "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. - Albert Schweitzer",
    "Failure is simply the opportunity to begin again, this time more intelligently. - Henry Ford",
    "The only place where success comes before work is in the dictionary. - Vidal Sassoon",
    "I failed my way to success. - Thomas Edison",
    "A person who never made a mistake never tried anything new. - Albert Einstein",
    "Success is how high you bounce when you hit bottom. - George S. Patton",
    "What seems to us as bitter trials are often blessings in disguise. - Oscar Wilde",
    "The secret of success is to do the common thing uncommonly well. - John D. Rockefeller Jr.",
    "Success is not the absence of failure; it's the persistence through failure. - Aisha Tyler",
    "I cannot give you the formula for success, but I can give you the formula for failure: It is: Try to please everybody. - Herbert Bayard Swope",
    "Success means doing the best we can with what we have. Success is the doing, not the getting; in the trying, not the triumph. - Zig Ziglar",
    "Success is to be measured not so much by the position that one has reached in life as by the obstacles which he has overcome. - Booker T. Washington",
    "Success is the sum of small efforts, repeated day in and day out. - Robert Collier",
    "Success is doing ordinary things extraordinarily well. - Jim Rohn",
    "It always seems impossible until it's done. - Nelson Mandela",
    "The only way to achieve the impossible is to believe it is possible. - Charles Kingsleigh",
    "Life is either a daring adventure or nothing at all. - Helen Keller",
    "It does not matter how slowly you go as long as you do not stop. - Confucius",
    "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
    "It is better to fail in originality than to succeed in imitation. - Herman Melville",
    "Don't count the days, make the days count. - Muhammad Ali",
    "The journey of a thousand miles begins with one step. - Lao Tzu",
    "Dream big and dare to fail. - Norman Vaughan",
    "Believe you can and you're halfway there. - Theodore Roosevelt",
    "Failure is not falling down, but refusing to get up. - Chinese Proverb",
    "Go confidently in the direction of your dreams. Live the life you have imagined. - Henry David Thoreau",
    "The only limit to our realization of tomorrow is our doubts of today. - Franklin D. Roosevelt",
    "Happiness is not something ready made. It comes from your own actions. - Dalai Lama",
    "A goal without a plan is just a wish. - Antoine de Saint-Exupéry",
    "Hardships often prepare ordinary people for an extraordinary destiny. - C.S. Lewis",
    "Success is not final, failure is not fatal: it is the courage to continue that counts. - Winston Churchill",
    "You miss 100% of the shots you don't take. - Wayne Gretzky",
    "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
    "Don't let the fear of losing be greater than the excitement of winning. - Robert Kiyosaki",
    "The only way to do great work is to love what you do. - Steve Jobs"
];

function generateQuote(){
    const randomIndex = Math.floor(Math.random() * quotes.length);
    document.getElementById('Quote').innerText = quotes[randomIndex];
}
